  -- User
  CREATE TABLE "CHANNEL_USERS" 
   (	"EMPID" NUMBER NOT NULL ENABLE, 
	"USERID" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"STATUS" NUMBER, 
	 PRIMARY KEY ("USERID");

-- USER_ROLE table for assiging the Role 
CREATE TABLE "TESTDB"."USER_ROLE" 
   (	"USERID" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"USER_ROLE" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("USERID", "USER_ROLE")