name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Qodana
        uses: jetbrains/qodana-action@v2024.1
        with:
          project-dir: .
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
